version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=ytb-video-sharing
    expose:
      - '5432'
    ports:
      - '5432:5432'

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api-gateways"
    depends_on:
      - postgres
    expose:
      - 5001
    volumes:
      - /app/node_modules
      - ./api-gateways:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_DB=ytb-video-sharing
      - POSTGRES_PASSWORD=1
      - POSTGRES_PORT=5432

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./web-apps
    depends_on:
      - api
    expose:
      - 3000
    volumes:
      - /app/node_modules
      - ./web-apps:/app

networks:
  postgres:
    driver: bridge